//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config';

export default [
  ...tanstackConfig,
  {
    ignores: [
      'eslint.config.js',
      'src/routeTree.gen.ts', // Auto-generated by TanStack Router
      '**/routeTree.gen.ts', // In case of nested routes
    ],
  },
];
