name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build TanStack app
        run: npm run build --filter=web-start
        env:
          NODE_ENV: production

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/web-start'
          command: deploy --compatibility-date 2024-10-01

      - name: Summary
        run: |
          echo "✅ Deployment to Cloudflare Workers Complete!"
          echo "- Site URL: https://tanstack-start-app.isaacgweber.workers.dev"
          echo "- Branch: ${{ github.ref_name }}"
          echo "- Commit: ${{ github.sha }}"